// This file is auto-generated by @hey-api/openapi-ts

export const AccountCreateSchema = {
    properties: {
        account_name: {
            type: 'string',
            title: 'Account Name'
        },
        auth_type: {
            type: 'string',
            enum: ['cookie', 'sessdata', 'qrcode'],
            title: 'Auth Type'
        },
        credentials: {
            additionalProperties: true,
            type: 'object',
            title: 'Credentials'
        }
    },
    type: 'object',
    required: ['account_name', 'auth_type', 'credentials'],
    title: 'AccountCreate'
} as const;

export const AccountPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        account_name: {
            type: 'string',
            title: 'Account Name'
        },
        auth_type: {
            type: 'string',
            title: 'Auth Type'
        },
        bilibili_uid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bilibili Uid'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        profile_info: {
            additionalProperties: true,
            type: 'object',
            title: 'Profile Info',
            default: {}
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'account_name', 'auth_type', 'is_active', 'created_at', 'updated_at'],
    title: 'AccountPublic'
} as const;

export const AccountUpdateSchema = {
    properties: {
        account_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Name'
        },
        auth_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['cookie', 'sessdata', 'qrcode']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auth Type'
        },
        credentials: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentials'
        }
    },
    type: 'object',
    title: 'AccountUpdate'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const FailedResourcePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        subscription_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subscription Id'
        },
        resource_id: {
            type: 'string',
            title: 'Resource Id'
        },
        resource_type: {
            type: 'string',
            title: 'Resource Type'
        },
        failed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Failed At'
        },
        retry_count: {
            type: 'integer',
            title: 'Retry Count'
        },
        last_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error'
        },
        resource_meta: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource Meta'
        }
    },
    type: 'object',
    required: ['id', 'subscription_id', 'resource_id', 'resource_type', 'failed_at', 'retry_count', 'last_error', 'resource_meta'],
    title: 'FailedResourcePublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LoginResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        user: {
            '$ref': '#/components/schemas/UserPublic'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['access_token', 'user', 'permissions'],
    title: 'LoginResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QRCodeCheckRequestSchema = {
    properties: {
        qrcode_key: {
            type: 'string',
            title: 'Qrcode Key'
        }
    },
    type: 'object',
    required: ['qrcode_key'],
    title: 'QRCodeCheckRequest'
} as const;

export const QRCodeCheckResponseSchema = {
    properties: {
        status: {
            type: 'string',
            enum: ['pending', 'scanned', 'confirmed', 'expired'],
            title: 'Status'
        },
        account: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AccountPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        credentials: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentials'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'QRCodeCheckResponse'
} as const;

export const QRCodeGenerateResponseSchema = {
    properties: {
        qrcode_key: {
            type: 'string',
            title: 'Qrcode Key'
        },
        qrcode_url: {
            type: 'string',
            title: 'Qrcode Url'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['qrcode_key', 'qrcode_url', 'expires_at'],
    title: 'QRCodeGenerateResponse'
} as const;

export const ResourceCountsSchema = {
    properties: {
        video: {
            type: 'integer',
            title: 'Video',
            default: 0
        },
        dynamic: {
            type: 'integer',
            title: 'Dynamic',
            default: 0
        },
        article: {
            type: 'integer',
            title: 'Article',
            default: 0
        }
    },
    type: 'object',
    title: 'ResourceCounts'
} as const;

export const SubscriptionCreateSchema = {
    properties: {
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        uploader_uid: {
            type: 'string',
            title: 'Uploader Uid'
        },
        sync_config: {
            '$ref': '#/components/schemas/SyncConfig'
        }
    },
    type: 'object',
    required: ['account_id', 'uploader_uid', 'sync_config'],
    title: 'SubscriptionCreate'
} as const;

export const SubscriptionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        uploader_uid: {
            type: 'string',
            title: 'Uploader Uid'
        },
        uploader_name: {
            type: 'string',
            title: 'Uploader Name'
        },
        uploader_avatar: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uploader Avatar'
        },
        uploader_info: {
            additionalProperties: true,
            type: 'object',
            title: 'Uploader Info'
        },
        sync_config: {
            additionalProperties: true,
            type: 'object',
            title: 'Sync Config'
        },
        is_paused: {
            type: 'boolean',
            title: 'Is Paused'
        },
        last_sync_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Sync At'
        },
        latest_sync_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Sync Status'
        },
        latest_sync_log_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Sync Log Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'account_id', 'uploader_uid', 'uploader_name', 'uploader_avatar', 'uploader_info', 'sync_config', 'is_paused', 'last_sync_at', 'created_at', 'updated_at'],
    title: 'SubscriptionPublic'
} as const;

export const SubscriptionUpdateSchema = {
    properties: {
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        sync_config: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SyncConfig'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'SubscriptionUpdate'
} as const;

export const SyncConfigSchema = {
    properties: {
        resource_types: {
            items: {
                type: 'string',
                enum: ['video', 'dynamic', 'article']
            },
            type: 'array',
            title: 'Resource Types',
            default: ['video', 'dynamic', 'article']
        },
        sync_frequency: {
            type: 'string',
            enum: ['1h', '6h', '1d', '1w', 'manual'],
            title: 'Sync Frequency',
            default: '6h'
        },
        history_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'History Limit',
            default: 50
        },
        batch_size: {
            type: 'integer',
            title: 'Batch Size',
            default: 50
        }
    },
    type: 'object',
    title: 'SyncConfig'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;