// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    account_name: string;
    auth_type: 'cookie' | 'sessdata' | 'qrcode';
    credentials: {
        [key: string]: unknown;
    };
};

export type auth_type = 'cookie' | 'sessdata' | 'qrcode';

export type AccountPublic = {
    id: string;
    user_id: string;
    account_name: string;
    auth_type: string;
    bilibili_uid?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    profile_info?: {
        [key: string]: unknown;
    };
    is_active: boolean;
    created_at: (string | null);
    updated_at: (string | null);
};

export type AccountUpdate = {
    account_name?: (string | null);
    auth_type?: ('cookie' | 'sessdata' | 'qrcode' | null);
    credentials?: ({
    [key: string]: unknown;
} | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FailedResourcePublic = {
    id: string;
    subscription_id: string;
    resource_id: string;
    resource_type: string;
    failed_at: string;
    retry_count: number;
    last_error: (string | null);
    resource_meta: ({
    [key: string]: unknown;
} | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LoginResponse = {
    access_token: string;
    token_type?: string;
    user: UserPublic;
    permissions: Array<(string)>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QRCodeCheckRequest = {
    qrcode_key: string;
};

export type QRCodeCheckResponse = {
    status: 'pending' | 'scanned' | 'confirmed' | 'expired';
    account?: (AccountPublic | null);
    credentials?: ({
    [key: string]: unknown;
} | null);
};

export type status = 'pending' | 'scanned' | 'confirmed' | 'expired';

export type QRCodeGenerateResponse = {
    qrcode_key: string;
    qrcode_url: string;
    expires_at: string;
};

export type ResourceCounts = {
    video?: number;
    dynamic?: number;
    article?: number;
};

export type SubscriptionCreate = {
    account_id: string;
    uploader_uid: string;
    sync_config: SyncConfig;
};

export type SubscriptionPublic = {
    id: string;
    user_id: string;
    account_id: string;
    uploader_uid: string;
    uploader_name: string;
    uploader_avatar: (string | null);
    uploader_info: {
        [key: string]: unknown;
    };
    sync_config: {
        [key: string]: unknown;
    };
    is_paused: boolean;
    last_sync_at: (string | null);
    latest_sync_status?: (string | null);
    latest_sync_log_id?: (string | null);
    created_at: (string | null);
    updated_at: (string | null);
};

export type SubscriptionUpdate = {
    account_id?: (string | null);
    sync_config?: (SyncConfig | null);
};

export type SyncConfig = {
    resource_types?: Array<('video' | 'dynamic' | 'article')>;
    sync_frequency?: '1h' | '6h' | '1d' | '1w' | 'manual';
    history_limit?: (number | null);
    batch_size?: number;
};

export type sync_frequency = '1h' | '6h' | '1d' | '1w' | 'manual';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    permissions?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminReadPermissionsData = {
    module?: (string | null);
};

export type AdminReadPermissionsResponse = (unknown);

export type AdminReadRolesResponse = (unknown);

export type AdminCreateRoleData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type AdminCreateRoleResponse = (unknown);

export type AdminReadRoleData = {
    roleId: string;
};

export type AdminReadRoleResponse = (unknown);

export type AdminUpdateRoleData = {
    requestBody: {
        [key: string]: unknown;
    };
    roleId: string;
};

export type AdminUpdateRoleResponse = (unknown);

export type AdminDeleteRoleData = {
    roleId: string;
};

export type AdminDeleteRoleResponse = (unknown);

export type AdminReadRolePermissionsData = {
    roleId: string;
};

export type AdminReadRolePermissionsResponse = (unknown);

export type AdminAssignPermissionToRoleData = {
    requestBody: {
        [key: string]: unknown;
    };
    roleId: string;
};

export type AdminAssignPermissionToRoleResponse = (unknown);

export type AdminRemovePermissionFromRoleData = {
    permissionId: string;
    roleId: string;
};

export type AdminRemovePermissionFromRoleResponse = (unknown);

export type AdminReadUserRolesData = {
    userId: string;
};

export type AdminReadUserRolesResponse = (unknown);

export type AdminAssignRoleToUserData = {
    requestBody: {
        [key: string]: unknown;
    };
    userId: string;
};

export type AdminAssignRoleToUserResponse = (unknown);

export type AdminRemoveRoleFromUserData = {
    roleId: string;
    userId: string;
};

export type AdminRemoveRoleFromUserResponse = (unknown);

export type BilibiliProxyBilibiliImageData = {
    url: string;
};

export type BilibiliProxyBilibiliImageResponse = (unknown);

export type BilibiliReadAccountsResponse = (Array<AccountPublic>);

export type BilibiliCreateAccountData = {
    requestBody: AccountCreate;
};

export type BilibiliCreateAccountResponse = (AccountPublic);

export type BilibiliReadAccountData = {
    accountId: string;
};

export type BilibiliReadAccountResponse = (AccountPublic);

export type BilibiliUpdateAccountData = {
    accountId: string;
    requestBody: AccountUpdate;
};

export type BilibiliUpdateAccountResponse = (AccountPublic);

export type BilibiliDeleteAccountData = {
    accountId: string;
};

export type BilibiliDeleteAccountResponse = (unknown);

export type BilibiliGenerateQrcodeResponse = (QRCodeGenerateResponse);

export type BilibiliCheckQrcodeData = {
    requestBody: QRCodeCheckRequest;
};

export type BilibiliCheckQrcodeResponse = (QRCodeCheckResponse);

export type BilibiliReadSubscriptionsResponse = (Array<SubscriptionPublic>);

export type BilibiliCreateSubscriptionData = {
    requestBody: SubscriptionCreate;
};

export type BilibiliCreateSubscriptionResponse = (unknown);

export type BilibiliReadSubscriptionData = {
    subId: string;
};

export type BilibiliReadSubscriptionResponse = (SubscriptionPublic);

export type BilibiliUpdateSubscriptionData = {
    requestBody: SubscriptionUpdate;
    subId: string;
};

export type BilibiliUpdateSubscriptionResponse = (unknown);

export type BilibiliDeleteSubscriptionData = {
    subId: string;
};

export type BilibiliDeleteSubscriptionResponse = (unknown);

export type BilibiliPauseSubscriptionData = {
    subId: string;
};

export type BilibiliPauseSubscriptionResponse = (unknown);

export type BilibiliSyncSubscriptionData = {
    subId: string;
};

export type BilibiliSyncSubscriptionResponse = (unknown);

export type BilibiliRetryFailedResourcesData = {
    subId: string;
};

export type BilibiliRetryFailedResourcesResponse = (unknown);

export type BilibiliGetFailedResourcesData = {
    subId: string;
};

export type BilibiliGetFailedResourcesResponse = (Array<FailedResourcePublic>);

export type BilibiliReadResourcesData = {
    endDate?: (string | null);
    keyword?: (string | null);
    page?: number;
    pageSize?: number;
    resourceType?: (string | null);
    startDate?: (string | null);
    subscriptionId?: (string | null);
};

export type BilibiliReadResourcesResponse = (unknown);

export type BilibiliReadResourceCountsData = {
    subscriptionId?: (string | null);
};

export type BilibiliReadResourceCountsResponse = (ResourceCounts);

export type BilibiliReadResourceData = {
    resourceId: string;
};

export type BilibiliReadResourceResponse = (unknown);

export type BilibiliReadSyncLogsData = {
    subscriptionId: string;
};

export type BilibiliReadSyncLogsResponse = (unknown);

export type BilibiliReadSyncLogData = {
    logId: string;
};

export type BilibiliReadSyncLogResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (LoginResponse);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);