/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutBilibiliRouteImport } from './routes/_layout/bilibili'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBilibiliIndexRouteImport } from './routes/_layout/bilibili/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutBilibiliSubscriptionsRouteImport } from './routes/_layout/bilibili/subscriptions'
import { Route as LayoutBilibiliAccountsRouteImport } from './routes/_layout/bilibili/accounts'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminRolesRouteImport } from './routes/_layout/admin/roles'
import { Route as LayoutAdminPermissionsRouteImport } from './routes/_layout/admin/permissions'
import { Route as LayoutBilibiliSubscriptionsIndexRouteImport } from './routes/_layout/bilibili/subscriptions/index'
import { Route as LayoutBilibiliSubscriptionsSubscriptionIdRouteImport } from './routes/_layout/bilibili/subscriptions/$subscriptionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBilibiliRoute = LayoutBilibiliRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBilibiliIndexRoute = LayoutBilibiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutBilibiliRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutBilibiliSubscriptionsRoute =
  LayoutBilibiliSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => LayoutBilibiliRoute,
  } as any)
const LayoutBilibiliAccountsRoute = LayoutBilibiliAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutBilibiliRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminRolesRoute = LayoutAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPermissionsRoute = LayoutAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutBilibiliSubscriptionsIndexRoute =
  LayoutBilibiliSubscriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutBilibiliSubscriptionsRoute,
  } as any)
const LayoutBilibiliSubscriptionsSubscriptionIdRoute =
  LayoutBilibiliSubscriptionsSubscriptionIdRouteImport.update({
    id: '/$subscriptionId',
    path: '/$subscriptionId',
    getParentRoute: () => LayoutBilibiliSubscriptionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/bilibili': typeof LayoutBilibiliRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/admin/permissions': typeof LayoutAdminPermissionsRoute
  '/admin/roles': typeof LayoutAdminRolesRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/bilibili/accounts': typeof LayoutBilibiliAccountsRoute
  '/bilibili/subscriptions': typeof LayoutBilibiliSubscriptionsRouteWithChildren
  '/admin/': typeof LayoutAdminIndexRoute
  '/bilibili/': typeof LayoutBilibiliIndexRoute
  '/bilibili/subscriptions/$subscriptionId': typeof LayoutBilibiliSubscriptionsSubscriptionIdRoute
  '/bilibili/subscriptions/': typeof LayoutBilibiliSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/permissions': typeof LayoutAdminPermissionsRoute
  '/admin/roles': typeof LayoutAdminRolesRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/bilibili/accounts': typeof LayoutBilibiliAccountsRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/bilibili': typeof LayoutBilibiliIndexRoute
  '/bilibili/subscriptions/$subscriptionId': typeof LayoutBilibiliSubscriptionsSubscriptionIdRoute
  '/bilibili/subscriptions': typeof LayoutBilibiliSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/bilibili': typeof LayoutBilibiliRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/permissions': typeof LayoutAdminPermissionsRoute
  '/_layout/admin/roles': typeof LayoutAdminRolesRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/bilibili/accounts': typeof LayoutBilibiliAccountsRoute
  '/_layout/bilibili/subscriptions': typeof LayoutBilibiliSubscriptionsRouteWithChildren
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/bilibili/': typeof LayoutBilibiliIndexRoute
  '/_layout/bilibili/subscriptions/$subscriptionId': typeof LayoutBilibiliSubscriptionsSubscriptionIdRoute
  '/_layout/bilibili/subscriptions/': typeof LayoutBilibiliSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/bilibili'
    | '/items'
    | '/settings'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/bilibili/accounts'
    | '/bilibili/subscriptions'
    | '/admin/'
    | '/bilibili/'
    | '/bilibili/subscriptions/$subscriptionId'
    | '/bilibili/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/items'
    | '/settings'
    | '/'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/bilibili/accounts'
    | '/admin'
    | '/bilibili'
    | '/bilibili/subscriptions/$subscriptionId'
    | '/bilibili/subscriptions'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/bilibili'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/permissions'
    | '/_layout/admin/roles'
    | '/_layout/admin/users'
    | '/_layout/bilibili/accounts'
    | '/_layout/bilibili/subscriptions'
    | '/_layout/admin/'
    | '/_layout/bilibili/'
    | '/_layout/bilibili/subscriptions/$subscriptionId'
    | '/_layout/bilibili/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bilibili': {
      id: '/_layout/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof LayoutBilibiliRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bilibili/': {
      id: '/_layout/bilibili/'
      path: '/'
      fullPath: '/bilibili/'
      preLoaderRoute: typeof LayoutBilibiliIndexRouteImport
      parentRoute: typeof LayoutBilibiliRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/bilibili/subscriptions': {
      id: '/_layout/bilibili/subscriptions'
      path: '/subscriptions'
      fullPath: '/bilibili/subscriptions'
      preLoaderRoute: typeof LayoutBilibiliSubscriptionsRouteImport
      parentRoute: typeof LayoutBilibiliRoute
    }
    '/_layout/bilibili/accounts': {
      id: '/_layout/bilibili/accounts'
      path: '/accounts'
      fullPath: '/bilibili/accounts'
      preLoaderRoute: typeof LayoutBilibiliAccountsRouteImport
      parentRoute: typeof LayoutBilibiliRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/roles': {
      id: '/_layout/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof LayoutAdminRolesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/permissions': {
      id: '/_layout/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof LayoutAdminPermissionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/bilibili/subscriptions/': {
      id: '/_layout/bilibili/subscriptions/'
      path: '/'
      fullPath: '/bilibili/subscriptions/'
      preLoaderRoute: typeof LayoutBilibiliSubscriptionsIndexRouteImport
      parentRoute: typeof LayoutBilibiliSubscriptionsRoute
    }
    '/_layout/bilibili/subscriptions/$subscriptionId': {
      id: '/_layout/bilibili/subscriptions/$subscriptionId'
      path: '/$subscriptionId'
      fullPath: '/bilibili/subscriptions/$subscriptionId'
      preLoaderRoute: typeof LayoutBilibiliSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof LayoutBilibiliSubscriptionsRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminPermissionsRoute: typeof LayoutAdminPermissionsRoute
  LayoutAdminRolesRoute: typeof LayoutAdminRolesRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminPermissionsRoute: LayoutAdminPermissionsRoute,
  LayoutAdminRolesRoute: LayoutAdminRolesRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutBilibiliSubscriptionsRouteChildren {
  LayoutBilibiliSubscriptionsSubscriptionIdRoute: typeof LayoutBilibiliSubscriptionsSubscriptionIdRoute
  LayoutBilibiliSubscriptionsIndexRoute: typeof LayoutBilibiliSubscriptionsIndexRoute
}

const LayoutBilibiliSubscriptionsRouteChildren: LayoutBilibiliSubscriptionsRouteChildren =
  {
    LayoutBilibiliSubscriptionsSubscriptionIdRoute:
      LayoutBilibiliSubscriptionsSubscriptionIdRoute,
    LayoutBilibiliSubscriptionsIndexRoute:
      LayoutBilibiliSubscriptionsIndexRoute,
  }

const LayoutBilibiliSubscriptionsRouteWithChildren =
  LayoutBilibiliSubscriptionsRoute._addFileChildren(
    LayoutBilibiliSubscriptionsRouteChildren,
  )

interface LayoutBilibiliRouteChildren {
  LayoutBilibiliAccountsRoute: typeof LayoutBilibiliAccountsRoute
  LayoutBilibiliSubscriptionsRoute: typeof LayoutBilibiliSubscriptionsRouteWithChildren
  LayoutBilibiliIndexRoute: typeof LayoutBilibiliIndexRoute
}

const LayoutBilibiliRouteChildren: LayoutBilibiliRouteChildren = {
  LayoutBilibiliAccountsRoute: LayoutBilibiliAccountsRoute,
  LayoutBilibiliSubscriptionsRoute:
    LayoutBilibiliSubscriptionsRouteWithChildren,
  LayoutBilibiliIndexRoute: LayoutBilibiliIndexRoute,
}

const LayoutBilibiliRouteWithChildren = LayoutBilibiliRoute._addFileChildren(
  LayoutBilibiliRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutBilibiliRoute: typeof LayoutBilibiliRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutBilibiliRoute: LayoutBilibiliRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
